# icon_map.py
icon_map = {
    ".3ga": "icons/3ga.png",
    ".3gp": "icons/3gp.png",
    ".7z": "icons/7z.png",
    ".aac": "icons/aac.png",
    ".accdb": "icons/accdb.png",
    ".aep": "icons/aep.png",
    ".ai": "icons/ai.png",
    ".amr": "icons/amr.png",
    ".apk": "icons/apk.png",
    ".asnt": "icons/asnt.png",
    ".asproj": "icons/asproj.png",
    ".awb": "icons/awb.png",
    ".backupbat": "icons/bat.png",  ####
    ".bin": "icons/bin.png",
    ".blend": "icons/blend.png",
    ".blend1": "icons/blend1.png",
    ".c": "icons/c.png",
    ".cdr": "icons/cdr.png",
    ".chm": "icons/chm.png",
    ".cpp": "icons/cpp.png",
    ".cs": "icons/cs.png",
    ".css": "icons/css.png",
    ".csv": "icons/csv.png",
    ".dart": "icons/dart.png",
    ".db": "icons/db.png",
    ".doc": "icons/doc.png",
    ".docx": "icons/docx.png",
    ".drawio": "icons/drawio.png",
    ".ejs": "icons/ejs.png",
    ".epub": "icons/epub.png",
    ".exe": "icons/exe.png",
    ".flac": "icons/flac.png",
    ".flp": "icons/flp.png",
    ".gz": "icons/tar-gz.png",
    ".htm": "icons/htm.png",
    ".html": "icons/html.png",
    ".img": "icons/img.png",
    ".ipynb": "icons/ipynb.png",
    ".iso": "icons/iso.png",
    ".jad": "icons/jad.png",
    ".jar": "icons/jar.png",
    ".java": "icons/java.png",
    ".ldf": "icons/ldf.png",
    ".lottie": "icons/lottie.png",
    ".js": "icons/js.png",
    ".json": "icons/json.png",
    ".jsx": "icons/jsx.png",
    ".m4a": "icons/m4a.png",
    ".mcworld": "icons/mcworld.png",
    ".mcpack": "icons/mcpack.png",
    ".mhtml": "icons/mhtml.png",
    ".md": "icons/md.png",
    ".mdf": "icons/mdf.png",
    ".mid": "icons/mid.png",
    ".mp3": "icons/mp3.png",
    # ".mp4": "icons/mp4.png"
    ".msi": "icons/msi.png",
    ".mup": "icons/mup.png",
    ".mwb": "icons/mwb.png",
    ".ods": "icons/ods.png",
    ".odt": "icons/odt.png",
    ".ogg": "icons/ogg.png",
    ".otf": "icons/otf.png",
    ".pas": "icons/pas.png",
    ".pdf": "icons/pdf.png",
    ".pka": "icons/pka.png",
    ".pkt": "icons/pkt.png",
    ".pps": "icons/pps.png",
    ".ppsx": "icons/ppsx.png",
    ".ppt": "icons/ppt.png",
    ".pptm": "icons/pptm.png",
    ".pptx": "icons/pptx.png",
    ".prproj": "icons/prproj.png",
    # ".ps1": "icons/ps1.png",
    ".psd": "icons/psd.png",
    ".py": "icons/py.png",
    ".rar": "icons/rar.png",
    ".reg": "icons/reg.png",
    ".rmskin": "icons/rmskin.png",
    ".rtf": "icons/rtf.png",
    ".sfd": "icons/sfd.png",
    # ".sh": "icons/sh.png",
    ".sql": "icons/sql.png",
    ".ssmssln": "icons/ssmssln.png",
    ".svg": "icons/svg.png",
    ".swf": "icons/swf.png",
    ".tar": "icons/tar.png",
    # ".tar.gz": "icons/tar-gz.png",
    # ".tar.xz": "icons/tar-xz.png",
    ".tbwf": "icons/tbwf.png",
    ".test": "icons/test.png",
    ".tmp": "icons/tmp.png",
    ".ttf": "icons/ttf.png",
    ".txt": "icons/txt.png",
    ".uhtml": "icons/uhtml.png",
    ".url": "icons/url.png",
    ".vcf": "icons/vcf.png",
    ".vob": "icons/vob.png",
    ".wav": "icons/wav.png",
    ".woff": "icons/woff.png",
    ".woff2": "icons/woff2.png",
    ".wma": "icons/wma.png",
    ".xapk": "icons/xapk.png",
    ".xls": "icons/xls.png",
    ".xlsm": "icons/xlsm.png",
    ".xlsx": "icons/xlsx.png",
    ".xml": "icons/xml.png",
    ".xmp": "icons/xmp.png",
    ".xz": "icons/tar-xz.png",
    ".zip": "icons/zip.png",
}

description_map = {
    ".3ga": "3GPP Audio File",
    ".3gp": "3GPP Multimedia File",
    ".7z": "7-Zip Compressed File",
    ".aac": "Advanced Audio Coding File",
    ".accdb": "Microsoft Access Database File",
    ".aep": "Adobe After Effects Project",
    ".ai": "Adobe Illustrator File",
    ".amr": "Adaptive Multi-Rate Audio File",
    ".apk": "Android Package File",
    ".arw": "Sony Alpha Raw Image File",
    ".asnt": "PubChemPy - Chemistry Related File",
    ".asproj": "Architecture Studio Project File",
    ".awb": "Adaptive Multi-Rate Wideband Audio File",
    ".backupbat": "Batch Script File", #####
    ".bin": "Binary File",
    ".blend": "Blender Project File",
    ".blend1": "Blender Backup File",
    ".c": "C Source Code File",
    ".cdr": "CorelDRAW Image File",
    ".chm": "Compiled HTML Help File",
    ".cpp": "C++ Source Code File",
    ".cs": "C# Source Code File",
    ".csv": "Comma Separated Values File",
    ".css": "Cascading Style Sheets File",
    ".dart": "Dart Programming Language Source File",
    ".db": "Database File",
    ".doc": "Microsoft Word Document (Legacy)",
    ".docx": "Microsoft Word Open XML Document",
    ".drawio": "Diagrams.net Drawing File",
    ".ejs": "Embedded JavaScript Template",
    ".epub": "Electronic Publication File",
    ".exe": "Executable File",
    ".flac": "Free Lossless Audio Codec File",
    ".flp": "FL Studio Project File",
    ".htm": "Hypertext Markup Language File",
    ".html": "Hypertext Markup Language Document",
    ".img": "Disc Image File",
    ".ipynb": "Jupyter Notebook File",
    ".iso": "ISO Disc Image File",
    ".jad": "Java Application Descriptor File",
    ".jar": "Java Archive File",
    ".java": "Java Source Code File",
    ".js": "JavaScript File",
    ".json": "JavaScript Object Notation File",
    ".jsx": "JavaScript XML File",
    ".ldf": "SQL Server Database Log File",
    ".lottie": "Lottie Animation File",
    ".m4a": "MPEG-4 Audio File",
    ".mcpack": "Minecraft Resource or Behavior Pack File",
    ".mcworld": "Minecraft World File",
    ".md": "Markdown Documentation File",
    ".mdf": "SQL Server Database Primary Data File",
    ".mid": "Musical Instrument Digital Interface File",
    ".mhtml": "MIME HTML Document",
    ".mp3": "MPEG Layer 3 Audio File",
    ".mp4": "MPEG-4 Video File",
    ".msi": "Windows Installer Package",
    ".mup": "MindMup Mind Map File",
    ".mwb": "MySQL Workbench Document",
    ".odt": "OpenDocument Text Document",
    ".ogg": "Ogg Vorbis Audio File",
    ".otf": "OpenType Font File",
    ".pas": "Pascal Source File",
    ".pdf": "Portable Document Format",
    ".pkt": "Cisco Packet Tracer Simulation File",
    ".pka": "Packet Tracer Activity File",
    ".pps": "Microsoft PowerPoint Slide Show (Legacy)",
    ".ppsx": "Microsoft PowerPoint Open XML Slide Show",
    ".ppt": "Microsoft PowerPoint Presentation (Legacy)",
    ".pptm": "Microsoft PowerPoint Macro-Enabled Presentation",
    ".pptx": "Microsoft PowerPoint Open XML Presentation",
    ".prproj": "Adobe Premiere Pro Project",
    ".ps1": "Windows PowerShell Script File",
    ".psd": "Adobe Photoshop Document",
    ".py": "Python Script File",
    ".rar": "RAR Compressed Archive File",
    ".raw": "Raw Image Data File",
    ".reg": "Registry File",
    ".rmskin": "Rainmeter Skin File",
    ".rtf": "Rich Text Format File",
    ".sfd": "Spline Font Database File",
    # ".sh": "Bash Shell Script",
    ".sql": "SQL Script File",
    ".ssmssln": "SQL Server Management Studio Solution File",
    ".svg": "Scalable Vector Graphics File",
    ".swf": "Shockwave Flash Movie",
    ".tar": "Consolidated Unix File Archive",
    # ".tar.gz": "Compressed Tarball File",
    # ".tar.xz": "XZ Compressed Tar Archive",
    ".gz": "Compressed Tarball File",
    ".xz": "XZ Compressed Tar Archive",
    ".tbwf": "Haylou/Amazfit/Zeblaze Watch Face File",
    ".test": "Test File",
    ".tmp": "Temporary File",
    ".ttf": "TrueType Font File",
    ".txt": "Plain Text File",
    ".uhtml": "Unified HTML File",
    ".url": "Uniform Resource Locator",
    ".vcf": "Virtual Contact File (vCard)",
    ".vob": "DVD Video Object File",
    ".wav": "Waveform Audio File Format",
    ".wma": "Windows Media Audio File",
    ".woff": "Web Open Font Format File",
    ".woff2": "Web Open Font Format 2.0 File",
    ".xls": "Microsoft Excel Spreadsheet (Legacy)",
    ".xlsm": "Microsoft Excel Macro-Enabled Spreadsheet",
    ".xlsx": "Microsoft Excel Open XML Spreadsheet",
    ".xml": "Extensible Markup Language File",
    ".xmp": "Extensible Metadata Platform File",
    ".xapk": "Extended Android Package File",
    ".zip": "ZIP Archive File"
}

